# Template pour les discussions GitHub

## Types de discussions

### 💡 Idées et suggestions
- Propositions de nouvelles fonctionnalités
- Améliorations de l'expérience utilisateur
- Optimisations de performance

### 🤔 Questions générales
- Questions sur l'utilisation
- Clarifications sur la documentation
- Conseils d'implémentation

### 🎯 Annonces
- Nouvelles versions
- Changements importants
- Événements communautaires

### 🛠️ Aide et support
- Problèmes d'installation
- Erreurs courantes
- Conseils de débogage

## Guidelines

- **Soyez respectueux** : Traitez les autres avec courtoisie
- **Recherchez d'abord** : Vérifiez si votre question a déjà été posée
- **Soyez spécifique** : Fournissez des détails et des exemples
- **Utilisez les labels** : Aidez à catégoriser votre discussion
- **Partagez vos solutions** : Si vous résolvez un problème, partagez la solution 